services:
  smartsyncserver:
    build: .
    container_name: smartsyncserver
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # Mount vault data directory
      - ./docker/vault:/vault
      # Mount config file (create this locally first)
      - ./docker/data:/data
      # Only mount if you want to manually replace executable
      # - ./docker/app:/app
