services:
  smartsyncserver:
    build: .
    container_name: smartsyncserver
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # Mount vault data directory
      - ./vault:/vault
      # Mount config file (create this locally first)
      - ./config.yaml:/app/config.yaml:ro
      # - ./checksums.json:/app/checksums.json:ro
      # Only mount if you want to manually replace executable
      # - ./docker/app:/app
